import Footer from "@/components/Footer";
import Navbar from "@/components/Nav";
import Swap from "@/components/Swap";

export const metadata = {
  title: "Hommies Swap",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
    <Navbar/>
    <Swap />
    <Footer />

    </>
  )
}
